name: 🐛 Bug Report - Extension Code
description: Report a bug in the extension's functionality, UI, or commands
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in the extension code! Please fill out the information below.
        
        **Note:** If your issue is with lesson content (typos, outdated instructions, incorrect commands), please use the "Bug Report - Lesson Content" template instead.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I click the "Show Welcome Page" button, nothing happens...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open VSCode
        2. Click on Tenstorrent sidebar
        3. Click "Show Welcome Page" button
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The welcome page should open in a webview panel
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Nothing happens, and I see an error in the console
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of the extension are you using?
      placeholder: "0.0.248"
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VSCode Version
      description: What version of VSCode are you using?
      placeholder: "1.93.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - RHEL 8
        - RHEL 9
        - Other Linux (please specify below)
    validations:
      required: true

  - type: input
    id: hardware
    attributes:
      label: Tenstorrent Hardware
      description: What hardware are you using?
      placeholder: "N150, N300, T3K, P100, P150, Galaxy, or None"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please copy any relevant logs or error messages. Check VSCode's Output panel (View → Output → select "Tenstorrent") and Developer Console (Help → Toggle Developer Tools).
      placeholder: |
        Paste error messages here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
